import sys
from pathlib import Path
ROOT_DIR = Path(__file__).parent.parent.resolve()
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

import streamlit as st

def render_user_manual_page():
    st.markdown("## 📖 User Manual & Setup Guide")
    st.markdown("Complete step-by-step instructions for registering sender emails, importing candidate spreadsheets, generating Word/PDF documents, and launching campaigns.")

    tab_smtp, tab_cand, tab_docs, tab_email, tab_faq = st.tabs([
        "📧 Sender Email & Gmail SMTP",
        "👥 Candidate Data & Excel",
        "📄 Word & PDF Documents",
        "🚀 Email Campaigns & Templates",
        "❓ Frequently Asked Questions"
    ])

    # Tab 1: Sender Email & Gmail SMTP Registration Setup
    with tab_smtp:
        st.markdown("### 📧 Registering Your Sender Email (Gmail SMTP Setup)")
        st.markdown("""
        To send live recruitment emails from your own Gmail address to candidates, Google requires an **App Password** for security.

        ---

        #### Step 1: Generate a 16-Character Google App Password
        1. Open your **Google Account Settings** at [myaccount.google.com](https://myaccount.google.com).
        2. Select **Security** on the left menu.
        3. Under *How you sign in to Google*, ensure **2-Step Verification** is turned **ON**.
        4. Search for **App Passwords** in the top search bar.
        5. Enter a custom name (e.g., `RecruitFlow`) and click **Create**.
        6. Copy the **16-character password** generated by Google (e.g. `abcd efgh ijkl mnop`).

        ---

        #### Step 2: Configure Credentials in Streamlit Cloud (or `.env`)
        - **If deployed on Streamlit Community Cloud**:
          1. Go to your app management page at [share.streamlit.io](https://share.streamlit.io).
          2. Click the **3 dots (`...`)** menu ➔ Select **Settings** ➔ Open **Secrets**.
          3. Paste your email and 16-character App Password:
             ```toml
             EMAIL_ADDRESS = "your_email@gmail.com"
             EMAIL_PASSWORD = "abcdefghijklmnop"
             ```
          4. Click **Save**.

        - **If running locally on your computer**:
          1. Open or create a file named `.env` in the root project folder.
          2. Add your credentials:
             ```text
             EMAIL_ADDRESS=your_email@gmail.com
             EMAIL_PASSWORD=abcdefghijklmnop
             ```

        ---

        #### Step 3: Switch Transmission Mode to Gmail SMTP
        1. Navigate to **⚙️ Settings** in the sidebar.
        2. Open the **Email Configuration** tab.
        3. Select **Gmail SMTP** as your Transmission Engine.
        """)

    # Tab 2: Candidate Data & Excel Import
    with tab_cand:
        st.markdown("### 👥 Candidate Import & Excel Management")
        st.markdown("""
        #### Option 1: Upload via Excel Spreadsheet (Recommended)
        1. Navigate to **👥 Candidates** from the main menu.
        2. Expand **Excel Management** and click **Download Sample Excel Template**.
        3. Fill in candidate records in `.xlsx` format. Ensure mandatory columns are filled:
           - `Candidate_ID` (e.g., `C001`, `C002`)
           - `Name` (Full Name)
           - `Email` (Valid candidate email address)
           - `Position` & `Department`
           - `Company` & `Joining_Date` (YYYY-MM-DD)
           - `Salary` (Numerical amount)
        4. Upload your filled spreadsheet into the **Drag & Drop Candidate Excel** box.
        5. Click **Import Candidates to Database**.

        #### Option 2: Add Candidate Manually
        1. Go to **👥 Candidates** ➔ Expand **Add / Edit / Delete Candidate Record**.
        2. Fill out candidate details in the **Add New Candidate** tab and click **Save Candidate**.
        """)

    # Tab 3: Document Generation (Word & PDF)
    with tab_docs:
        st.markdown("### 📄 Generating Offer Letters & Certificates")
        st.markdown("""
        RecruitFlow automatically generates dual-format documents (**Word `.docx`** and **PDF `.pdf`**):

        1. Select candidates in **👥 Candidates** (using checkboxes in Table or Card view).
        2. Navigate to **📄 Documents** in the sidebar.
        3. Choose document package: **Offer Letter**, **Certificate**, or **Both**.
        4. Click **Generate Documents Now**.
        5. View generated files in the **Document Archives** table below with single-click download buttons for both `.docx` and `.pdf` files.
        """)

    # Tab 4: Email Automation & Campaign Dispatch
    with tab_email:
        st.markdown("### 🚀 Dynamic Email Personalization & Campaign Launch")
        st.markdown("""
        #### Personalization Placeholders
        Use dynamic tags in your email subjects and body templates:
        - `{{name}}` or `{Name}` : Candidate's Full Name
        - `{{candidate_id}}` or `{Candidate_ID}` : Candidate ID
        - `{{position}}` or `{Position}` : Position Title
        - `{{department}}` or `{Department}` : Department
        - `{{company}}` or `{Company}` : Company Name
        - `{{joining_date}}` or `{Joining_Date}` : Proposed Joining Date
        - `{{salary}}` or `{Salary}` : Formatted Salary

        #### Dispatching Emails:
        1. Select recipients in **👥 Candidates**.
        2. Go to **📧 Email Automation**.
        3. Compose subject & body text or select a predefined template.
        4. Choose document attachments (*Offer Letter*, *Certificate*, *Both*, *None*).
        5. Review rendered text in the **Email Preview Panel**.
        6. Confirm checkbox and click **Confirm & Send Email 🚀**.
        7. Audit dispatch results in **📜 Email History**. Click **Retry Send** if any email fails.
        """)

    # Tab 5: FAQ
    with tab_faq:
        st.markdown("### ❓ Frequently Asked Questions")
        st.markdown("""
        **Q: What is Demo Mode vs Gmail SMTP Mode?**  
        *A: Demo Mode simulates email sending for offline testing and presentations without needing real passwords. Gmail SMTP connects to live Google servers to deliver actual emails.*

        **Q: Can candidates see each other's emails?**  
        *A: No. Every email is dispatched individually to each candidate. There is zero CC or BCC data leakage.*

        **Q: How do I switch between Dark and Light mode?**  
        *A: Use the **App Theme Preference** dropdown in the top left sidebar or inside **⚙️ Settings**.*
        """)
