import streamlit as st
import os
from database.database import get_setting, set_setting
from utils.auth import get_current_user

def render_settings_page():
    st.markdown("## System Settings & Configuration")
    st.markdown("Configure HR profile details, email transmission modes, Gmail SMTP credentials, and application preferences.")

    user = get_current_user()

    # Tabbed Settings
    tab_profile, tab_email, tab_app = st.tabs(["Profile", "Email Configuration", "Application Settings"])

    with tab_profile:
        st.markdown("### HR Profile Settings")
        with st.form("form_profile_settings"):
            p_name = st.text_input("Name", value=user["name"])
            p_email = st.text_input("Email Address", value=user["email"])
            p_role = st.text_input("Role Title", value=user["role"])

            submit_p = st.form_submit_button("Update Profile")
            if submit_p:
                st.session_state["user_name"] = p_name
                st.session_state["user_email"] = p_email
                st.session_state["user_role"] = p_role
                set_setting("hr_name", p_name)
                set_setting("hr_email", p_email)
                st.success("Profile details updated successfully.")
                st.rerun()

    with tab_email:
        st.markdown("### Email Dispatch Mode")
        current_mode = get_setting("email_mode", "Demo Mode")

        new_mode = st.radio(
            "Transmission Engine",
            ["Demo Mode", "Gmail SMTP"],
            index=0 if current_mode == "Demo Mode" else 1,
            help="Demo Mode simulates sending and logs entries to SQLite without requiring real Gmail credentials. Gmail SMTP connects to live Google servers."
        )

        if new_mode != current_mode:
            set_setting("email_mode", new_mode)
            st.success(f"Email Dispatch Mode updated to **{new_mode}**.")
            st.rerun()

        st.markdown("---")

        st.markdown("### Gmail SMTP Credentials")
        env_email = os.getenv("EMAIL_ADDRESS") or get_setting("sender_email", "hr@abctechnologies.com")
        has_pass = bool(os.getenv("EMAIL_PASSWORD") or get_setting("sender_password", ""))

        st.text_input("Sender Email Address", value=env_email, disabled=True, key="dis_email_addr")
        st.text_input("Gmail App Password Status", value="••••••••••••••••" if has_pass else "Not Configured", disabled=True, key="dis_email_pass")

        with st.expander("How to Set Up Gmail App Password (Step-by-Step Guide)", expanded=False):
            st.markdown("""
            To send actual live emails through Gmail SMTP, Google requires an **App Password** (not your regular Gmail login password).

            #### Instructions:
            1. Log into your **Google Account** at [myaccount.google.com](https://myaccount.google.com).
            2. Navigate to **Security** on the left menu.
            3. Under *How you sign in to Google*, ensure **2-Step Verification** is turned **ON**.
            4. Search for **App Passwords** in the top search bar.
            5. Select **Mail** as the app and **Other (Custom Name)** as the device (e.g. *RecruitFlow*).
            6. Click **Generate** and copy the 16-character password generated by Google (e.g., `abcd efgh ijkl mnop`).
            7. Save your credentials in your `.env` file or Streamlit Secrets:
            ```text
            EMAIL_ADDRESS=your_email@gmail.com
            EMAIL_PASSWORD=abcdefghijklmnop
            ```
            > **Security Notice**: Never commit your 16-character App Password to public GitHub repositories.
            """)

    with tab_app:
        st.markdown("### Application Preferences")
        
        c_confirm = get_setting("confirm_before_send", "True") == "True"
        c_history = get_setting("save_email_history", "True") == "True"
        c_autogen = get_setting("auto_gen_docs", "False") == "True"
        c_notif = get_setting("show_notifications", "True") == "True"

        with st.form("form_app_preferences"):
            f_confirm = st.checkbox("Confirm before sending emails", value=c_confirm)
            f_history = st.checkbox("Save email history logs", value=c_history)
            f_autogen = st.checkbox("Automatically generate missing documents on send", value=c_autogen)
            f_notif = st.checkbox("Show system notifications", value=c_notif)

            submit_app = st.form_submit_button("Save Application Preferences")
            if submit_app:
                set_setting("confirm_before_send", str(f_confirm))
                set_setting("save_email_history", str(f_history))
                set_setting("auto_gen_docs", str(f_autogen))
                set_setting("show_notifications", str(f_notif))
                st.success("Application preferences updated successfully.")
                st.rerun()
