import streamlit as st
import os
from database.database import get_setting, set_setting

def render_settings_page():
    st.markdown("## ⚙️ System Settings & Configuration")
    st.markdown("Configure email transmission modes, Gmail SMTP credentials, sender profiles, and corporate metadata.")

    # 1. Email Transmission Mode Setting
    st.markdown("### 1. Email Dispatch Mode")
    current_mode = get_setting("email_mode", "Demo Mode")

    new_mode = st.radio(
        "Transmission Engine",
        ["Demo Mode", "Gmail SMTP"],
        index=0 if current_mode == "Demo Mode" else 1,
        help="Demo Mode simulates sending and logs entries to SQLite without requiring real Gmail credentials. Gmail SMTP connects to live Google servers."
    )

    if new_mode != current_mode:
        set_setting("email_mode", new_mode)
        st.success(f"Email Dispatch Mode updated to **{new_mode}**!")
        st.rerun()

    st.markdown("---")

    # 2. Gmail SMTP Credentials
    st.markdown("### 2. Gmail SMTP Credentials")
    env_email = os.getenv("EMAIL_ADDRESS") or get_setting("sender_email", "hr@abctechnologies.com")
    has_pass = bool(os.getenv("EMAIL_PASSWORD") or get_setting("sender_password", ""))

    st.text_input("Sender Email Address", value=env_email, disabled=True, key="dis_email_addr")
    st.text_input("Gmail App Password Status", value="••••••••••••••••" if has_pass else "Not Configured", disabled=True, key="dis_email_pass")

    with st.expander("🔑 How to Set Up Gmail App Password (Step-by-Step Guide)", expanded=False):
        st.markdown("""
        To send actual live emails through Gmail SMTP, Google requires an **App Password** (not your regular Gmail login password).

        #### Instructions:
        1. Log into your **Google Account** at [myaccount.google.com](https://myaccount.google.com).
        2. Navigate to **Security** on the left menu.
        3. Under *How you sign in to Google*, ensure **2-Step Verification** is turned **ON**.
        4. Search for **App Passwords** in the top search bar.
        5. Select **Mail** as the app and **Other (Custom Name)** as the device (e.g. *RecruitFlow*).
        6. Click **Generate** and copy the 16-character password generated by Google (e.g., `abcd efgh ijkl mnop`).
        7. Save your credentials in your `.env` file or Streamlit Secrets:
        ```text
        EMAIL_ADDRESS=your_email@gmail.com
        EMAIL_PASSWORD=abcdefghijklmnop
        ```
        > 🔒 **Security Notice**: Never commit your 16-character App Password to public GitHub repositories!
        """)

    st.markdown("---")

    # 3. Company Metadata Configuration
    st.markdown("### 3. Corporate Metadata & Branding")

    comp_name = get_setting("company_name", "ABC Technologies")
    hr_name = get_setting("hr_name", "Recruitment Team")
    hr_email = get_setting("hr_email", "hr@abctechnologies.com")
    comp_addr = get_setting("company_address", "Tech Park, Innovation Way, Suite 500")

    with st.form("form_company_metadata"):
        st.caption("These values populate header lines and signatory blocks in generated Offer Letters and Certificates.")
        f_comp_name = st.text_input("Company Name", value=comp_name)
        f_hr_name = st.text_input("HR Signatory Name / Department", value=hr_name)
        f_hr_email = st.text_input("HR Contact Email", value=hr_email)
        f_comp_addr = st.text_area("Company Address", value=comp_addr, height=80)

        submit_meta = st.form_submit_button("Save Corporate Settings")
        if submit_meta:
            set_setting("company_name", f_comp_name)
            set_setting("hr_name", f_hr_name)
            set_setting("hr_email", f_hr_email)
            set_setting("company_address", f_comp_addr)
            st.success("Corporate metadata updated successfully!")
            st.rerun()
